Git use cases tutorial
aimclub/open-source-ops pull request #59
Opened 2023-07-24 08:21 UTC by pvkvetkin

Туториал по гиту состоит из:

- вводной информации по гиту, основные понятие при работе с Git
- основные команды Git
- GitFlow сценарии

2023-07-26 10:25 UTC, nicl-nno commented
Добавил бы ещё сценарий актуализации fork-версии при обновлении базового репо.

2023-07-28 17:39 UTC, andreygetmanov requested changes
В туториале есть много команд-примеров, но почти нет объяснения работы разных параметров команд. С другой стороны, просто перечислять, что делают команды `-m`, `-f` и т.д. - по сути копировать документацию. Как мне кажется, можно при упоминании какой-либо команды давать ссылку на [документацию](https://git-scm.com/docs) по ней, а в этом туториале рассмотреть самые частые примеры использования

2023-07-28 17:39 UTC, andreygetmanov commented on tutorials/git_flow.md
> +`git clone <URL>`: клонирование удаленного репозитория Git в локальную директорию - загружаются все коммиты, ветки и файлы из удаленного репозитория и создается локальная копию проекта
Можно ещё добавить информации про наиболее используемые параметры команд (типа `--mirror`, `--branch` и т.д.). Их можно найти [здесь](https://github.com/git-guides/git-clone) и дополнить частью [отсюда](https://git-scm.com/docs/git-clone)

2023-07-28 17:39 UTC, andreygetmanov commented on tutorials/git_flow.md
> +`git add <file/dir>`: индексация файлы или директория для коммита
Здесь тоже можно указать параметры, которые чаще всего используются (типа `git add .`)

2023-08-20 15:23 UTC, pvkvetkin commented on tutorials/git_flow.md
> +Git - это распределенная система управления версиями, разработанная Линусом Торвальдсом. Она позволяет разработчикам эффективно управлять и отслеживать изменения в исходном коде проекта. Git предоста
Согласен, дополнил, переформулировал.

2023-08-20 15:23 UTC, pvkvetkin commented on tutorials/git_flow.md
> +- Ветвление (Branching) - это создание новой ветки на основе существующей. Это позволяет разработчикам работать над различными фичами или задачами независимо друг от друга. Каждая ветка имеет свою со
Согласен, переместил.

2023-08-20 15:23 UTC, pvkvetkin commented on tutorials/git_flow.md
> +`git clone <URL>`: клонирование удаленного репозитория Git в локальную директорию - загружаются все коммиты, ветки и файлы из удаленного репозитория и создается локальная копию проекта
Исправил.

2023-08-20 15:24 UTC, pvkvetkin commented on tutorials/git_flow.md
> +### Внесение изменений
Дополнил.

2023-08-20 15:24 UTC, pvkvetkin commented on tutorials/git_flow.md
> +`git checkout <branch>`: переключение между ветками
Дополнил.

2023-08-20 15:24 UTC, pvkvetkin commented on tutorials/git_flow.md
> +`git pull`: взятие всех изменений из удаленного репозитория и слиянение этих изменений с текущей веткой
Добавил.

2023-09-21 18:57 UTC, nicl-nno approved these changes

2023-09-21 18:58 UTC, merged